[package]
name = "embedded-sdmmc"
version = "0.3.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
description = "A basic SD/MMC driver for Embedded Rust."
keywords = ["sdcard", "mmc", "embedded", "fat32"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/thejpster/embedded-sdmmc-rs"
edition = "2018"
readme = "README.md"

[dependencies]
embedded-hal = "0.2.2"
byteorder = { version = "1", default-features = false }
nb = "0.1"
log = "0.4"

[dependencies.stm32h7xx-hal]
path = "../stm32h7xx-hal"
features = ["stm32h743v", "rt", "sdmmc"]

[dev-dependencies]
env_logger = "0.7"
